export enum LoyaltyPointsSource {
  ORDER = 'ORDER', //POR COMPRAS
  PAYMENT = 'PAYMENT', //POR METODO DE PAGO
  REFERRAL = 'REFERRAL', //CAMPAÑAS
  PROMOTION = 'PROMOTION', //REFERIDO
  MANUAL_ADJUST = 'MANUAL_ADJUST', //AJUSTE MANUAL
}
