/**
 * Numeric `feature.id` from subscription reference seed (see
 * `scripts/seed-subscriptions-reference-data.sql` INSERT INTO feature, ids 1–116).
 * Used with `@RequireFeature` / `FeatureAccessGuard`.
 */
export const SUBSCRIPTION_FEATURE_IDS = {
  // 1-13 platform / backoffice
  CENTRAL_BACKOFFICE: 1,
  CLIENT_BACKOFFICE: 2,
  COMPANIES: 3,
  MERCHANTS: 4,
  APPLICATIONS: 5,
  SUBSCRIPTION_FEATURES_CATALOG: 6,
  MERCHANT_SUBSCRIPTIONS: 7,
  PLAN_APPLICATIONS: 8,
  PLAN_FEATURES: 9,
  SUBSCRIPTION_PLANS: 10,
  SUBSCRIPTION_APPLICATIONS: 11,
  SUBSCRIPTION_PAYMENTS: 12,
  USERS: 13,
  // Billing / transactions
  RECEIPT_ITEMS: 14,
  RECEIPTS: 15,
  RECEIPTS_TAXES: 16,
  // Configuration
  MERCHANT_OVERTIME_RULES: 17,
  MERCHANT_PAYROLL_RULES: 18,
  MERCHANT_TAX_RULES: 19,
  MERCHANT_TIPS_RULES: 20,
  // Financial engine
  JOURNAL_ENTRIES: 21,
  JOURNAL_ENTRY_LINES: 22,
  LEDGER_ACCOUNTS: 23,
  // Business partners
  CUSTOMERS: 24,
  SUPPLIERS: 25,
  // Accounts payable
  SUPPLIER_CREDIT_NOTES: 26,
  SUPPLIER_INVOICE_ITEMS: 27,
  SUPPLIER_INVOICES: 28,
  SUPPLIER_PAYMENT_ITEMS: 29,
  SUPPLIER_PAYMENTS: 30,
  SUPPLIER_PAYMENTS_ALLOCATION: 31,
  // HR
  COLLABORATORS: 32,
  COLLABORATOR_CONTRACTS: 33,
  COLLABORATOR_TIME_ENTRIES: 34,
  // Payroll
  PAYROLL_ADJUSTMENTS: 35,
  PAYROLL_ENTRIES: 36,
  PAYROLL_RUNS: 37,
  PAYROLL_TAX_DETAIL: 38,
  // Food costing
  ACTUAL_COST_VARIANCE: 39,
  RECIPE_INGREDIENTS: 40,
  RECIPES: 41,
  THEORETICAL_COST: 42,
  // Inventory
  CATEGORY_MANAGEMENT: 43,
  MODIFIERS_MANAGEMENT: 44,
  PRODUCT_MANAGEMENT: 45,
  PURCHASE_ORDERS_MANAGEMENT: 46,
  STOCK_AND_STOCK_MOVEMENTS: 47,
  SUPPLIERS_MANAGEMENT: 48,
  VARIANTS_MANAGEMENT: 49,
  // Dining
  FLOOR_PLANS: 50,
  TABLE_ASSIGNMENTS: 51,
  TABLE_ZONES: 52,
  TABLES: 53,
  // KDS
  KITCHEN_DISPLAY_DEVICES: 54,
  KITCHEN_EVENT_LOG: 55,
  KITCHEN_ORDER_ITEMS: 56,
  KITCHEN_ORDERS: 57,
  KITCHEN_STATIONS: 58,
  // POS
  ORDER_DISCOUNTS: 59,
  ORDER_ITEMS: 60,
  ORDER_PAYMENTS: 61,
  ORDER_TAXES: 62,
  ORDERS: 63,
  ORDER_ITEM_MODIFIERS: 64,
  CASH_DRAWER_HISTORY: 65,
  CASH_DRAWERS: 66,
  CASH_TRANSACTIONS: 67,
  SHIFT_ASSIGNMENT: 68,
  SHIFTS: 69,
  // Tips
  TIP_MOVEMENTS: 70,
  TIP_POOL_MEMBERS: 71,
  TIP_SETTLEMENTS: 72,
  TIPS: 73,
  TIPS_ALLOCATIONS: 74,
  TIPS_POOLS: 75,
  // Reservations (if APIs exist)
  RESERVATIONS: 76,
  RESERVATION_GUESTS: 77,
  RESERVATION_NOTES: 78,
  RESERVATION_STATUS_HISTORY: 79,
  RESERVATION_TABLES: 80,
  TABLE_TURNOVER_OPTIMIZATION: 81,
  // Delivery management
  DELIVERY_ASSIGNMENTS: 82,
  DELIVERY_DRIVERS: 83,
  DELIVERY_FEES: 84,
  DELIVERY_TRACKING: 85,
  DELIVERY_ZONES: 86,
  // Online ordering
  ONLINE_DELIVERY_INFO: 87,
  ONLINE_MENU_CATEGORIES: 88,
  ONLINE_MENU_ITEMS: 89,
  ONLINE_MENUS: 90,
  ONLINE_ORDER_ITEMS: 91,
  ONLINE_ORDERS: 92,
  ONLINE_PAYMENTS: 93,
  ONLINE_STORES: 94,
  // QR
  QR_CODE_LOCATIONS: 95,
  QR_CODE_MENU_ITEMS: 96,
  QR_CODE_MENU_SECTIONS: 97,
  QR_CODE_MENUS: 98,
  QR_CODE_ORDERS: 99,
  QR_ORDER_ITEMS: 100,
  // Loyalty
  LOYALTY_CUSTOMERS: 101,
  LOYALTY_COUPONS: 102,
  LOYALTY_POINT_TRANSACTIONS: 103,
  LOYALTY_PROGRAMS: 104,
  LOYALTY_REWARDS: 105,
  LOYALTY_REWARDS_REDEMPTIONS: 106,
  LOYALTY_TIERS: 107,
  // Marketing
  MARKETING_AUTOMATION: 108,
  MARKETING_AUTOMATION_ACTION: 109,
  MARKETING_CAMPAIGN: 110,
  MARKETING_CAMPAIGN_AUDIENCE: 111,
  MARKETING_COUPON: 112,
  MARKETING_COUPON_REDEMPTION: 113,
  MARKETING_MESSAGE_LOG: 114,
  MARKETING_SEGMENT: 115,
  MARKETING_SEGMENT_RULE: 116,
} as const;

export type SubscriptionFeatureIdKey = keyof typeof SUBSCRIPTION_FEATURE_IDS;

export type SubscriptionFeatureId =
  (typeof SUBSCRIPTION_FEATURE_IDS)[SubscriptionFeatureIdKey];

/** All numeric ids from the subscription catalog (platform / portal users bypassing plan check). */
export function getAllSubscriptionFeatureIds(): number[] {
  return Object.values(SUBSCRIPTION_FEATURE_IDS).sort((a, b) => a - b);
}
