-- Reference data: subscription plans, applications, features, plan_applications, plan_features
-- Defaults: subscription_plan.price=0, billingCycle=monthly, status=active;
-- plan_applications.limits=unlimited; plan_features.limit_value=0 (uncapped placeholder in seed).
-- Dimension rows use ON CONFLICT (id) DO UPDATE so existing FKs (e.g. merchant_subscription) are not broken.
-- Junction rows for plans 1–3 are replaced after DELETE.
/*
--- Copy below for story / ticket comment (AC 6) ---

BEGIN;

-- Junction data only (safe if no unexpected FKs point at these rows)
DELETE FROM plan_features WHERE subscription_plan_id IN (1, 2, 3);
DELETE FROM plan_applications WHERE subscriptionplan_id IN (1, 2, 3);

INSERT INTO subscription_plan (id, name, description, price, "billingCycle", status) VALUES
  (1, 'Quick Service', 'For Quick Service restaurant without table operations', 0, 'monthly', 'active'),
  (2, 'Full Restaurant', 'For Full Service restaurant with table operations and other features', 0, 'monthly', 'active'),
  (3, 'Enterprise', 'Include premium features', 0, 'monthly', 'active')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  "billingCycle" = EXCLUDED."billingCycle",
  status = EXCLUDED.status;

INSERT INTO application (id, name, description, category, status) VALUES
  (1, 'Central Backoffice', 'Central Backoffice Manage', 'Platform SaaS', 'active'),
  (2, 'Client Backoffice', 'Client Backoffice Manage', 'Platform SaaS', 'active'),
  (3, 'Companies', 'Companies Manage', 'Platform SaaS', 'active'),
  (4, 'Merchants', 'Merchants Manage', 'Platform SaaS', 'active'),
  (5, 'Subscription System', 'Subscription System Manage', 'Platform SaaS', 'active'),
  (6, 'Users', 'Users Manage', 'Platform SaaS', 'active'),
  (7, 'Billing / Transactions', 'Billing / Transactions Manage', 'CORE', 'active'),
  (8, 'Configuration', 'Configuration Manage', 'CORE', 'active'),
  (9, 'Financial Engine', 'Financial Engine Manage', 'CORE', 'active'),
  (10, 'Business Partners', 'Business Partners Manage', 'CORE', 'active'),
  (11, 'Accounts Payable', 'Accounts Payable manage', 'Finance & HR', 'active'),
  (12, 'HR', 'Human resources manage', 'Finance & HR', 'active'),
  (13, 'Payrolls', 'Payrolls manage', 'Finance & HR', 'active'),
  (14, 'Food Costing', 'Food Costing manage', 'Inventory', 'active'),
  (15, 'Products/Inventory System', 'Products/Inventory System', 'Inventory', 'active'),
  (16, 'Dining System', 'Dining System Manage', 'Restaurant Operations', 'active'),
  (17, 'Kitchen Display System', 'Kitchen Display System', 'Restaurant Operations', 'active'),
  (18, 'POS', 'POS Manage', 'Restaurant Operations', 'active'),
  (19, 'Cash Drawers', 'Cash Drawers Manage', 'Restaurant Operations', 'active'),
  (20, 'Shifts', 'Shifts Manage', 'Restaurant Operations', 'active'),
  (21, 'Tips', 'Tips Manage', 'Restaurant Operations', 'active'),
  (22, 'Reservations', 'Reservations Manage', 'Restaurant Operations', 'active'),
  (23, 'Table Turnover Optimization', 'Table Turnover Optimization Manage', 'Restaurant Operations', 'active'),
  (24, 'Delivery Management', 'Delivery Management Manage', 'Commerce', 'active'),
  (25, 'Online Ordering System', 'Online Ordering System Manage', 'Commerce', 'active'),
  (26, 'QR Code System', 'QR Code System Manage', 'Commerce', 'active'),
  (27, 'Loyalty System', 'Loyalty System Manage', 'Growth', 'active'),
  (28, 'Marketing System', 'Marketing System Manage', 'Growth', 'active')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  status = EXCLUDED.status;

INSERT INTO feature (id, name, description, "Unit", status) VALUES
  (1, 'Central Backoffice (to be defined)', 'Central Backoffice managed from central backoffice application', 'Unit', 'active'),
  (2, 'Client Backoffice (to be defined)', 'Client Backoffice managed from client backoffice application', 'Unit', 'active'),
  (3, 'Companies', 'Companies managed from Companies application', 'Unit', 'active'),
  (4, 'Merchants', 'Merchants managed from Merchants application', 'Unit', 'active'),
  (5, 'Applications', 'Applications managed from Subscription System  application', 'Unit', 'active'),
  (6, 'Features', 'Features managed from Subscription System  application', 'Unit', 'active'),
  (7, 'Merchant Subscriptions', 'Merchant Subscriptions managed from Subscription System  application', 'Unit', 'active'),
  (8, 'Plan applications', 'Plan applications managed from Subscription System  application', 'Unit', 'active'),
  (9, 'Plan features', 'Plan features managed from Subscription System  application', 'Unit', 'active'),
  (10, 'Subcription Plans', 'Subcription Plans managed from Subscription System  application', 'Unit', 'active'),
  (11, 'Subscription Applications', 'Subscription Applications managed from Subscription System  application', 'Unit', 'active'),
  (12, 'Subscription payments', 'Subscription payments managed from Subscription System  application', 'Unit', 'active'),
  (13, 'Users', 'Users managed from Users application', 'Unit', 'active'),
  (14, 'Receipt items', 'Receipt items managed from Billing / Transactions application', 'Unit', 'active'),
  (15, 'Receipts', 'Receipts managed from Billing / Transactions application', 'Unit', 'active'),
  (16, 'Receipts taxes', 'Receipts taxes managed from Billing / Transactions application', 'Unit', 'active'),
  (17, 'Merchant Overtime Rules', 'Merchant Overtime Rules managed from Configuration application', 'Unit', 'active'),
  (18, 'Merchant Payroll Rules', 'Merchant Payroll Rules managed from Configuration application', 'Unit', 'active'),
  (19, 'Merchant Tax Rules', 'Merchant Tax Rules managed from Configuration application', 'Unit', 'active'),
  (20, 'Merchant Tips Rules', 'Merchant Tips Rules managed from Configuration application', 'Unit', 'active'),
  (21, 'Journal Entries', 'Journal Entries managed from Financial Engine application', 'Unit', 'active'),
  (22, 'Journal Entries lines', 'Journal Entries lines managed from Financial Engine application', 'Unit', 'active'),
  (23, 'Ledger Accounts', 'Ledger Accounts managed from Financial Engine application', 'Unit', 'active'),
  (24, 'Customers', 'Customers managed from Business Partners application', 'Unit', 'active'),
  (25, 'Suppliers', 'Suppliers managed from Business Partners application', 'Unit', 'active'),
  (26, 'Supplier Credit Notes', 'Supplier Credit Notes managed from Accounts Payable application', 'Unit', 'active'),
  (27, 'Supplier Invoice Items', 'Supplier Invoice Items managed from Accounts Payable application', 'Unit', 'active'),
  (28, 'Supplier Invoices', 'Supplier Invoices managed from Accounts Payable application', 'Unit', 'active'),
  (29, 'Supplier Payment Items', 'Supplier Payment Items managed from Accounts Payable application', 'Unit', 'active'),
  (30, 'Supplier Payments', 'Supplier Payments managed from Accounts Payable application', 'Unit', 'active'),
  (31, 'Supplier Payments Allocation', 'Supplier Payments Allocation managed from Accounts Payable application', 'Unit', 'active'),
  (32, 'Collaborators', 'Collaborators managed from HR application', 'Unit', 'active'),
  (33, 'Collaborators Contracts', 'Collaborators Contracts managed from HR application', 'Unit', 'active'),
  (34, 'Collaborators Time Entries', 'Collaborators Time Entries managed from HR application', 'Unit', 'active'),
  (35, 'Payroll Adjustments', 'Payroll Adjustments managed from Payrolls application', 'Unit', 'active'),
  (36, 'Payroll Entries', 'Payroll Entries managed from Payrolls application', 'Unit', 'active'),
  (37, 'Payroll Runs', 'Payroll Runs managed from Payrolls application', 'Unit', 'active'),
  (38, 'Payroll Tax Detail', 'Payroll Tax Detail managed from Payrolls application', 'Unit', 'active'),
  (39, 'Actual Cost Variance', ' Actual Cost Variance managed from Food Costing application', 'Unit', 'active'),
  (40, 'Recipe Ingredients', 'Recipe Ingredients managed from Food Costing application', 'Unit', 'active'),
  (41, 'Recipes', 'Recipes managed from Food Costing application', 'Unit', 'active'),
  (42, 'Theoretical Cost', 'Theoretical Cost managed from Food Costing application', 'Unit', 'active'),
  (43, 'Category Management', 'Category Management managed from Products/Inventory System application', 'Unit', 'active'),
  (44, 'Modifiers Management', 'Modifiers Management managed from Products/Inventory System application', 'Unit', 'active'),
  (45, 'Product Managment', 'Product Managment managed from Products/Inventory System application', 'Unit', 'active'),
  (46, 'Purchase Orders Management', 'Purchase Orders Management managed from Products/Inventory System application', 'Unit', 'active'),
  (47, 'Stock and Stock Movements Management', 'Stock and Stock Movements Management managed from Products/Inventory System application', 'Unit', 'active'),
  (48, 'Suppliers Management', 'Suppliers Management managed from Products/Inventory System application', 'Unit', 'active'),
  (49, 'Variants Management', 'Variants Management managed from Products/Inventory System application', 'Unit', 'active'),
  (50, 'Floor plans', 'Floor plans managed from Dining System application', 'Unit', 'active'),
  (51, 'Table asignments', 'Table asignments managed from Dining System application', 'Unit', 'active'),
  (52, 'Table Zones', 'Table Zones managed from Dining System application', 'Unit', 'active'),
  (53, 'Tables', 'Tables managed from Dining System application', 'Unit', 'active'),
  (54, 'Kitchen Display Devices', 'Kitchen Display Devices managed from Kitchen Display System application', 'Unit', 'active'),
  (55, 'Kitchen Event Log', 'Kitchen Event Log managed from Kitchen Display System application', 'Unit', 'active'),
  (56, 'Kitchen Order Items', 'Kitchen Order Items managed from Kitchen Display System application', 'Unit', 'active'),
  (57, 'Kitchen Orders', 'Kitchen Orders managed from Kitchen Display System application', 'Unit', 'active'),
  (58, 'Kitchen Stations', 'Kitchen Stations managed from Kitchen Display System application', 'Unit', 'active'),
  (59, 'Order Discounts', 'Order Discounts managed from POS application', 'Unit', 'active'),
  (60, 'Order Items', 'Order Items managed from POS application', 'Unit', 'active'),
  (61, 'Order Payments', 'Order Payments managed from POS application', 'Unit', 'active'),
  (62, 'Order Taxes', 'Order Taxes managed from POS application', 'Unit', 'active'),
  (63, 'Orders', 'Orders managed from POS application', 'Unit', 'active'),
  (64, 'Order Item Modifiers', 'Order Item Modifiers managed from POS application', 'Unit', 'active'),
  (65, 'Cash Drawer History', 'Cash Drawer History managed from Cash Drawers application', 'Unit', 'active'),
  (66, 'Cash Drawers', 'Cash Drawers managed from Cash Drawers application', 'Unit', 'active'),
  (67, 'Cash Transactions', 'Cash Transactions managed from Cash Drawers application', 'Unit', 'active'),
  (68, 'Shift Assignment', 'Shift Assignment managed from Shifts application', 'Unit', 'active'),
  (69, 'Shifts', 'Shifts managed from Shifts application', 'Unit', 'active'),
  (70, 'Tip movements', 'Tip movements managed from Tips application', 'Unit', 'active'),
  (71, 'Tip pool members', 'Tip pool members managed from Tips application', 'Unit', 'active'),
  (72, 'Tip settlements', 'Tip settlements managed from Tips application', 'Unit', 'active'),
  (73, 'Tips', 'Tips managed from Tips application', 'Unit', 'active'),
  (74, 'Tips Allocations', 'Tips Allocations managed from Tips application', 'Unit', 'active'),
  (75, 'Tips pools', 'Tips pools managed from Tips application', 'Unit', 'active'),
  (76, 'Reservations', 'Reservations managed from Reservations application', 'Unit', 'active'),
  (77, 'Reservation Guests', 'Reservation Guests managed from Reservations application', 'Unit', 'active'),
  (78, 'Reservation Notes', 'Reservation Notes managed from Reservations application', 'Unit', 'active'),
  (79, 'Reservation Status History', 'Reservation Status History managed from Reservations application', 'Unit', 'active'),
  (80, 'Reservation Tables', 'Reservation Tables managed from Reservations application', 'Unit', 'active'),
  (81, 'Table Turnover Optimization', 'Table Turnover Optimization managed from Table Turnover Optimization application', 'Unit', 'active'),
  (82, 'Delivery Assignments', 'Delivery Assignments managed from Delivery Management application', 'Unit', 'active'),
  (83, 'Delivery Drivers', 'Delivery Drivers managed from Delivery Management application', 'Unit', 'active'),
  (84, 'Delivery Fees', 'Delivery Fees managed from Delivery Management application', 'Unit', 'active'),
  (85, 'Delivery Tracking', 'Delivery Tracking managed from Delivery Management application', 'Unit', 'active'),
  (86, 'Delivery Zones', 'Delivery Zones managed from Delivery Management application', 'Unit', 'active'),
  (87, 'Online Delivery Info', 'Online Delivery Info managed from Online Ordering System application', 'Unit', 'active'),
  (88, 'Online Menu Categories', 'Online Menu Categories managed from Online Ordering System application', 'Unit', 'active'),
  (89, 'Online Menu Items', 'Online Menu Items managed from Online Ordering System application', 'Unit', 'active'),
  (90, 'Online Menus', 'Online Menus managed from Online Ordering System application', 'Unit', 'active'),
  (91, 'Online Order Items', 'Online Order Items managed from Online Ordering System application', 'Unit', 'active'),
  (92, 'Online Orders', 'Online Orders managed from Online Ordering System application', 'Unit', 'active'),
  (93, 'Online Payments', 'Online Payments managed from Online Ordering System application', 'Unit', 'active'),
  (94, 'Online Stores', 'Online Stores managed from Online Ordering System application', 'Unit', 'active'),
  (95, 'QR Code Locations', 'QR Code Locations managed from QR Code System application', 'Unit', 'active'),
  (96, 'QR Code Menu Items', 'QR Code Menu Items managed from QR Code System application', 'Unit', 'active'),
  (97, 'QR Code Menu Sections', 'QR Code Menu Sections managed from QR Code System application', 'Unit', 'active'),
  (98, 'QR Code Menus', 'QR Code Menus managed from QR Code System application', 'Unit', 'active'),
  (99, 'QR Code Orders', 'QR Code Orders managed from QR Code System application', 'Unit', 'active'),
  (100, 'QR Order Items', 'QR Order Items managed from QR Code System application', 'Unit', 'active'),
  (101, 'Loyalty costumers', 'Loyalty costumers managed from Loyalty System application', 'Unit', 'active'),
  (102, 'Loyalty coupons', 'Loyalty coupons managed from Loyalty System application', 'Unit', 'active'),
  (103, 'Loyalty point transactions', 'Loyalty point transactions managed from Loyalty System application', 'Unit', 'active'),
  (104, 'Loyalty Programs', 'Loyalty Programs managed from Loyalty System application', 'Unit', 'active'),
  (105, 'Loyalty rewards', 'Loyalty rewards managed from Loyalty System application', 'Unit', 'active'),
  (106, 'Loyalty rewards redemptions', 'Loyalty rewards redemptions managed from Loyalty System application', 'Unit', 'active'),
  (107, 'Loyalty tiers', 'Loyalty tiers managed from Loyalty System application', 'Unit', 'active'),
  (108, 'Marketing Automation', 'Marketing Automation managed from Loyalty System application Marketing System', 'Unit', 'active'),
  (109, 'Marketing Automation Action', 'Marketing Automation Action managed from Loyalty System application Marketing System', 'Unit', 'active'),
  (110, 'Marketing Campaign', 'Marketing Campaign managed from Loyalty System application Marketing System', 'Unit', 'active'),
  (111, 'Marketing Campaign Audience', 'Marketing Campaign Audience managed from Loyalty System application Marketing System', 'Unit', 'active'),
  (112, 'Marketing Coupon', 'Marketing Coupon managed from Loyalty System application Marketing System', 'Unit', 'active'),
  (113, 'Marketing Coupon Redemption', 'Marketing Coupon Redemption managed from Loyalty System application Marketing System', 'Unit', 'active'),
  (114, 'Marketing Message Log', 'Marketing Message Log managed from Loyalty System application Marketing System', 'Unit', 'active'),
  (115, 'Marketing Segment', 'Marketing Segment managed from Loyalty System application Marketing System', 'Unit', 'active'),
  (116, 'Marketing Segment Rule', 'Marketing Segment Rule managed from Loyalty System application Marketing System', 'Unit', 'active')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  "Unit" = EXCLUDED."Unit",
  status = EXCLUDED.status;

INSERT INTO plan_applications (subscriptionplan_id, application_id, limits, status) VALUES
  (1, 1, 'unlimited', 'active'),
  (1, 2, 'unlimited', 'active'),
  (1, 3, 'unlimited', 'active'),
  (1, 4, 'unlimited', 'active'),
  (1, 5, 'unlimited', 'active'),
  (1, 6, 'unlimited', 'active'),
  (1, 7, 'unlimited', 'active'),
  (1, 10, 'unlimited', 'active'),
  (1, 15, 'unlimited', 'active'),
  (1, 16, 'unlimited', 'active'),
  (1, 17, 'unlimited', 'active'),
  (1, 18, 'unlimited', 'active'),
  (1, 19, 'unlimited', 'active'),
  (1, 20, 'unlimited', 'active'),
  (1, 25, 'unlimited', 'active'),
  (2, 1, 'unlimited', 'active'),
  (2, 2, 'unlimited', 'active'),
  (2, 3, 'unlimited', 'active'),
  (2, 4, 'unlimited', 'active'),
  (2, 5, 'unlimited', 'active'),
  (2, 6, 'unlimited', 'active'),
  (2, 7, 'unlimited', 'active'),
  (2, 8, 'unlimited', 'active'),
  (2, 9, 'unlimited', 'active'),
  (2, 10, 'unlimited', 'active'),
  (2, 11, 'unlimited', 'active'),
  (2, 12, 'unlimited', 'active'),
  (2, 13, 'unlimited', 'active'),
  (2, 14, 'unlimited', 'active'),
  (2, 15, 'unlimited', 'active'),
  (2, 16, 'unlimited', 'active'),
  (2, 17, 'unlimited', 'active'),
  (2, 18, 'unlimited', 'active'),
  (2, 19, 'unlimited', 'active'),
  (2, 20, 'unlimited', 'active'),
  (2, 21, 'unlimited', 'active'),
  (2, 22, 'unlimited', 'active'),
  (2, 23, 'unlimited', 'active'),
  (2, 24, 'unlimited', 'active'),
  (2, 25, 'unlimited', 'active'),
  (2, 26, 'unlimited', 'active'),
  (3, 1, 'unlimited', 'active'),
  (3, 2, 'unlimited', 'active'),
  (3, 3, 'unlimited', 'active'),
  (3, 4, 'unlimited', 'active'),
  (3, 5, 'unlimited', 'active'),
  (3, 6, 'unlimited', 'active'),
  (3, 7, 'unlimited', 'active'),
  (3, 8, 'unlimited', 'active'),
  (3, 9, 'unlimited', 'active'),
  (3, 10, 'unlimited', 'active'),
  (3, 11, 'unlimited', 'active'),
  (3, 12, 'unlimited', 'active'),
  (3, 13, 'unlimited', 'active'),
  (3, 14, 'unlimited', 'active'),
  (3, 15, 'unlimited', 'active'),
  (3, 16, 'unlimited', 'active'),
  (3, 17, 'unlimited', 'active'),
  (3, 18, 'unlimited', 'active'),
  (3, 19, 'unlimited', 'active'),
  (3, 20, 'unlimited', 'active'),
  (3, 21, 'unlimited', 'active'),
  (3, 22, 'unlimited', 'active'),
  (3, 23, 'unlimited', 'active'),
  (3, 24, 'unlimited', 'active'),
  (3, 25, 'unlimited', 'active'),
  (3, 26, 'unlimited', 'active'),
  (3, 27, 'unlimited', 'active'),
  (3, 28, 'unlimited', 'active');

INSERT INTO plan_features (subscription_plan_id, feature_id, limit_value, status) VALUES
  (1, 1, 0, 'active'),
  (1, 2, 0, 'active'),
  (1, 3, 0, 'active'),
  (1, 4, 0, 'active'),
  (1, 5, 0, 'active'),
  (1, 6, 0, 'active'),
  (1, 7, 0, 'active'),
  (1, 8, 0, 'active'),
  (1, 9, 0, 'active'),
  (1, 10, 0, 'active'),
  (1, 11, 0, 'active'),
  (1, 12, 0, 'active'),
  (1, 13, 0, 'active'),
  (1, 14, 0, 'active'),
  (1, 15, 0, 'active'),
  (1, 16, 0, 'active'),
  (1, 24, 0, 'active'),
  (1, 43, 0, 'active'),
  (1, 44, 0, 'active'),
  (1, 45, 0, 'active'),
  (1, 49, 0, 'active'),
  (1, 53, 0, 'active'),
  (1, 56, 0, 'active'),
  (1, 57, 0, 'active'),
  (1, 59, 0, 'active'),
  (1, 60, 0, 'active'),
  (1, 61, 0, 'active'),
  (1, 62, 0, 'active'),
  (1, 63, 0, 'active'),
  (1, 64, 0, 'active'),
  (1, 66, 0, 'active'),
  (1, 67, 0, 'active'),
  (1, 69, 0, 'active'),
  (1, 91, 0, 'active'),
  (1, 92, 0, 'active'),
  (1, 93, 0, 'active'),
  (2, 1, 0, 'active'),
  (2, 2, 0, 'active'),
  (2, 3, 0, 'active'),
  (2, 4, 0, 'active'),
  (2, 5, 0, 'active'),
  (2, 6, 0, 'active'),
  (2, 7, 0, 'active'),
  (2, 8, 0, 'active'),
  (2, 9, 0, 'active'),
  (2, 10, 0, 'active'),
  (2, 11, 0, 'active'),
  (2, 12, 0, 'active'),
  (2, 13, 0, 'active'),
  (2, 14, 0, 'active'),
  (2, 15, 0, 'active'),
  (2, 16, 0, 'active'),
  (2, 17, 0, 'active'),
  (2, 18, 0, 'active'),
  (2, 19, 0, 'active'),
  (2, 20, 0, 'active'),
  (2, 21, 0, 'active'),
  (2, 22, 0, 'active'),
  (2, 23, 0, 'active'),
  (2, 24, 0, 'active'),
  (2, 25, 0, 'active'),
  (2, 26, 0, 'active'),
  (2, 27, 0, 'active'),
  (2, 28, 0, 'active'),
  (2, 29, 0, 'active'),
  (2, 30, 0, 'active'),
  (2, 31, 0, 'active'),
  (2, 32, 0, 'active'),
  (2, 33, 0, 'active'),
  (2, 34, 0, 'active'),
  (2, 35, 0, 'active'),
  (2, 36, 0, 'active'),
  (2, 37, 0, 'active'),
  (2, 38, 0, 'active'),
  (2, 39, 0, 'active'),
  (2, 40, 0, 'active'),
  (2, 41, 0, 'active'),
  (2, 42, 0, 'active'),
  (2, 43, 0, 'active'),
  (2, 44, 0, 'active'),
  (2, 45, 0, 'active'),
  (2, 46, 0, 'active'),
  (2, 47, 0, 'active'),
  (2, 48, 0, 'active'),
  (2, 49, 0, 'active'),
  (2, 50, 0, 'active'),
  (2, 51, 0, 'active'),
  (2, 52, 0, 'active'),
  (2, 53, 0, 'active'),
  (2, 54, 0, 'active'),
  (2, 55, 0, 'active'),
  (2, 56, 0, 'active'),
  (2, 57, 0, 'active'),
  (2, 58, 0, 'active'),
  (2, 59, 0, 'active'),
  (2, 60, 0, 'active'),
  (2, 61, 0, 'active'),
  (2, 62, 0, 'active'),
  (2, 63, 0, 'active'),
  (2, 64, 0, 'active'),
  (2, 65, 0, 'active'),
  (2, 66, 0, 'active'),
  (2, 67, 0, 'active'),
  (2, 68, 0, 'active'),
  (2, 69, 0, 'active'),
  (2, 70, 0, 'active'),
  (2, 71, 0, 'active'),
  (2, 72, 0, 'active'),
  (2, 73, 0, 'active'),
  (2, 74, 0, 'active'),
  (2, 75, 0, 'active'),
  (2, 76, 0, 'active'),
  (2, 77, 0, 'active'),
  (2, 78, 0, 'active'),
  (2, 79, 0, 'active'),
  (2, 80, 0, 'active'),
  (2, 81, 0, 'active'),
  (2, 82, 0, 'active'),
  (2, 83, 0, 'active'),
  (2, 84, 0, 'active'),
  (2, 85, 0, 'active'),
  (2, 86, 0, 'active'),
  (2, 87, 0, 'active'),
  (2, 88, 0, 'active'),
  (2, 89, 0, 'active'),
  (2, 90, 0, 'active'),
  (2, 91, 0, 'active'),
  (2, 92, 0, 'active'),
  (2, 93, 0, 'active'),
  (2, 94, 0, 'active'),
  (2, 95, 0, 'active'),
  (2, 96, 0, 'active'),
  (2, 97, 0, 'active'),
  (2, 98, 0, 'active'),
  (2, 99, 0, 'active'),
  (2, 100, 0, 'active'),
  (3, 1, 0, 'active'),
  (3, 2, 0, 'active'),
  (3, 3, 0, 'active'),
  (3, 4, 0, 'active'),
  (3, 5, 0, 'active'),
  (3, 6, 0, 'active'),
  (3, 7, 0, 'active'),
  (3, 8, 0, 'active'),
  (3, 9, 0, 'active'),
  (3, 10, 0, 'active'),
  (3, 11, 0, 'active'),
  (3, 12, 0, 'active'),
  (3, 13, 0, 'active'),
  (3, 14, 0, 'active'),
  (3, 15, 0, 'active'),
  (3, 16, 0, 'active'),
  (3, 17, 0, 'active'),
  (3, 18, 0, 'active'),
  (3, 19, 0, 'active'),
  (3, 20, 0, 'active'),
  (3, 21, 0, 'active'),
  (3, 22, 0, 'active'),
  (3, 23, 0, 'active'),
  (3, 24, 0, 'active'),
  (3, 25, 0, 'active'),
  (3, 26, 0, 'active'),
  (3, 27, 0, 'active'),
  (3, 28, 0, 'active'),
  (3, 29, 0, 'active'),
  (3, 30, 0, 'active'),
  (3, 31, 0, 'active'),
  (3, 32, 0, 'active'),
  (3, 33, 0, 'active'),
  (3, 34, 0, 'active'),
  (3, 35, 0, 'active'),
  (3, 36, 0, 'active'),
  (3, 37, 0, 'active'),
  (3, 38, 0, 'active'),
  (3, 39, 0, 'active'),
  (3, 40, 0, 'active'),
  (3, 41, 0, 'active'),
  (3, 42, 0, 'active'),
  (3, 43, 0, 'active'),
  (3, 44, 0, 'active'),
  (3, 45, 0, 'active'),
  (3, 46, 0, 'active'),
  (3, 47, 0, 'active'),
  (3, 48, 0, 'active'),
  (3, 49, 0, 'active'),
  (3, 50, 0, 'active'),
  (3, 51, 0, 'active'),
  (3, 52, 0, 'active'),
  (3, 53, 0, 'active'),
  (3, 54, 0, 'active'),
  (3, 55, 0, 'active'),
  (3, 56, 0, 'active'),
  (3, 57, 0, 'active'),
  (3, 58, 0, 'active'),
  (3, 59, 0, 'active'),
  (3, 60, 0, 'active'),
  (3, 61, 0, 'active'),
  (3, 62, 0, 'active'),
  (3, 63, 0, 'active'),
  (3, 64, 0, 'active'),
  (3, 65, 0, 'active'),
  (3, 66, 0, 'active'),
  (3, 67, 0, 'active'),
  (3, 68, 0, 'active'),
  (3, 69, 0, 'active'),
  (3, 70, 0, 'active'),
  (3, 71, 0, 'active'),
  (3, 72, 0, 'active'),
  (3, 73, 0, 'active'),
  (3, 74, 0, 'active'),
  (3, 75, 0, 'active'),
  (3, 76, 0, 'active'),
  (3, 77, 0, 'active'),
  (3, 78, 0, 'active'),
  (3, 79, 0, 'active'),
  (3, 80, 0, 'active'),
  (3, 81, 0, 'active'),
  (3, 82, 0, 'active'),
  (3, 83, 0, 'active'),
  (3, 84, 0, 'active'),
  (3, 85, 0, 'active'),
  (3, 86, 0, 'active'),
  (3, 87, 0, 'active'),
  (3, 88, 0, 'active'),
  (3, 89, 0, 'active'),
  (3, 90, 0, 'active'),
  (3, 91, 0, 'active'),
  (3, 92, 0, 'active'),
  (3, 93, 0, 'active'),
  (3, 94, 0, 'active'),
  (3, 95, 0, 'active'),
  (3, 96, 0, 'active'),
  (3, 97, 0, 'active'),
  (3, 98, 0, 'active'),
  (3, 99, 0, 'active'),
  (3, 100, 0, 'active'),
  (3, 101, 0, 'active'),
  (3, 102, 0, 'active'),
  (3, 103, 0, 'active'),
  (3, 104, 0, 'active'),
  (3, 105, 0, 'active'),
  (3, 106, 0, 'active'),
  (3, 107, 0, 'active'),
  (3, 108, 0, 'active'),
  (3, 109, 0, 'active'),
  (3, 110, 0, 'active'),
  (3, 111, 0, 'active'),
  (3, 112, 0, 'active'),
  (3, 113, 0, 'active'),
  (3, 114, 0, 'active'),
  (3, 115, 0, 'active'),
  (3, 116, 0, 'active');

SELECT setval(pg_get_serial_sequence('subscription_plan', 'id'), (SELECT COALESCE(MAX(id), 1) FROM subscription_plan));
SELECT setval(pg_get_serial_sequence('application', 'id'), (SELECT COALESCE(MAX(id), 1) FROM application));
SELECT setval(pg_get_serial_sequence('feature', 'id'), (SELECT COALESCE(MAX(id), 1) FROM feature));
SELECT setval(pg_get_serial_sequence('plan_applications', 'id'), (SELECT COALESCE(MAX(id), 1) FROM plan_applications));
SELECT setval(pg_get_serial_sequence('plan_features', 'id'), (SELECT COALESCE(MAX(id), 1) FROM plan_features));
COMMIT;

--- End comment block ---
*/
BEGIN;

-- Junction data only (safe if no unexpected FKs point at these rows)
DELETE FROM plan_features WHERE subscription_plan_id IN (1, 2, 3);
DELETE FROM plan_applications WHERE subscriptionplan_id IN (1, 2, 3);

INSERT INTO subscription_plan (id, name, description, price, "billingCycle", status) VALUES
  (1, 'Quick Service', 'For Quick Service restaurant without table operations', 0, 'monthly', 'active'),
  (2, 'Full Restaurant', 'For Full Service restaurant with table operations and other features', 0, 'monthly', 'active'),
  (3, 'Enterprise', 'Include premium features', 0, 'monthly', 'active')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  price = EXCLUDED.price,
  "billingCycle" = EXCLUDED."billingCycle",
  status = EXCLUDED.status;

INSERT INTO application (id, name, description, category, status) VALUES
  (1, 'Central Backoffice', 'Central Backoffice Manage', 'Platform SaaS', 'active'),
  (2, 'Client Backoffice', 'Client Backoffice Manage', 'Platform SaaS', 'active'),
  (3, 'Companies', 'Companies Manage', 'Platform SaaS', 'active'),
  (4, 'Merchants', 'Merchants Manage', 'Platform SaaS', 'active'),
  (5, 'Subscription System', 'Subscription System Manage', 'Platform SaaS', 'active'),
  (6, 'Users', 'Users Manage', 'Platform SaaS', 'active'),
  (7, 'Billing / Transactions', 'Billing / Transactions Manage', 'CORE', 'active'),
  (8, 'Configuration', 'Configuration Manage', 'CORE', 'active'),
  (9, 'Financial Engine', 'Financial Engine Manage', 'CORE', 'active'),
  (10, 'Business Partners', 'Business Partners Manage', 'CORE', 'active'),
  (11, 'Accounts Payable', 'Accounts Payable manage', 'Finance & HR', 'active'),
  (12, 'HR', 'Human resources manage', 'Finance & HR', 'active'),
  (13, 'Payrolls', 'Payrolls manage', 'Finance & HR', 'active'),
  (14, 'Food Costing', 'Food Costing manage', 'Inventory', 'active'),
  (15, 'Products/Inventory System', 'Products/Inventory System', 'Inventory', 'active'),
  (16, 'Dining System', 'Dining System Manage', 'Restaurant Operations', 'active'),
  (17, 'Kitchen Display System', 'Kitchen Display System', 'Restaurant Operations', 'active'),
  (18, 'POS', 'POS Manage', 'Restaurant Operations', 'active'),
  (19, 'Cash Drawers', 'Cash Drawers Manage', 'Restaurant Operations', 'active'),
  (20, 'Shifts', 'Shifts Manage', 'Restaurant Operations', 'active'),
  (21, 'Tips', 'Tips Manage', 'Restaurant Operations', 'active'),
  (22, 'Reservations', 'Reservations Manage', 'Restaurant Operations', 'active'),
  (23, 'Table Turnover Optimization', 'Table Turnover Optimization Manage', 'Restaurant Operations', 'active'),
  (24, 'Delivery Management', 'Delivery Management Manage', 'Commerce', 'active'),
  (25, 'Online Ordering System', 'Online Ordering System Manage', 'Commerce', 'active'),
  (26, 'QR Code System', 'QR Code System Manage', 'Commerce', 'active'),
  (27, 'Loyalty System', 'Loyalty System Manage', 'Growth', 'active'),
  (28, 'Marketing System', 'Marketing System Manage', 'Growth', 'active')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  status = EXCLUDED.status;

INSERT INTO feature (id, name, description, "Unit", status) VALUES
  (1, 'Central Backoffice (to be defined)', 'Central Backoffice managed from central backoffice application', 'Unit', 'active'),
  (2, 'Client Backoffice (to be defined)', 'Client Backoffice managed from client backoffice application', 'Unit', 'active'),
  (3, 'Companies', 'Companies managed from Companies application', 'Unit', 'active'),
  (4, 'Merchants', 'Merchants managed from Merchants application', 'Unit', 'active'),
  (5, 'Applications', 'Applications managed from Subscription System  application', 'Unit', 'active'),
  (6, 'Features', 'Features managed from Subscription System  application', 'Unit', 'active'),
  (7, 'Merchant Subscriptions', 'Merchant Subscriptions managed from Subscription System  application', 'Unit', 'active'),
  (8, 'Plan applications', 'Plan applications managed from Subscription System  application', 'Unit', 'active'),
  (9, 'Plan features', 'Plan features managed from Subscription System  application', 'Unit', 'active'),
  (10, 'Subcription Plans', 'Subcription Plans managed from Subscription System  application', 'Unit', 'active'),
  (11, 'Subscription Applications', 'Subscription Applications managed from Subscription System  application', 'Unit', 'active'),
  (12, 'Subscription payments', 'Subscription payments managed from Subscription System  application', 'Unit', 'active'),
  (13, 'Users', 'Users managed from Users application', 'Unit', 'active'),
  (14, 'Receipt items', 'Receipt items managed from Billing / Transactions application', 'Unit', 'active'),
  (15, 'Receipts', 'Receipts managed from Billing / Transactions application', 'Unit', 'active'),
  (16, 'Receipts taxes', 'Receipts taxes managed from Billing / Transactions application', 'Unit', 'active'),
  (17, 'Merchant Overtime Rules', 'Merchant Overtime Rules managed from Configuration application', 'Unit', 'active'),
  (18, 'Merchant Payroll Rules', 'Merchant Payroll Rules managed from Configuration application', 'Unit', 'active'),
  (19, 'Merchant Tax Rules', 'Merchant Tax Rules managed from Configuration application', 'Unit', 'active'),
  (20, 'Merchant Tips Rules', 'Merchant Tips Rules managed from Configuration application', 'Unit', 'active'),
  (21, 'Journal Entries', 'Journal Entries managed from Financial Engine application', 'Unit', 'active'),
  (22, 'Journal Entries lines', 'Journal Entries lines managed from Financial Engine application', 'Unit', 'active'),
  (23, 'Ledger Accounts', 'Ledger Accounts managed from Financial Engine application', 'Unit', 'active'),
  (24, 'Customers', 'Customers managed from Business Partners application', 'Unit', 'active'),
  (25, 'Suppliers', 'Suppliers managed from Business Partners application', 'Unit', 'active'),
  (26, 'Supplier Credit Notes', 'Supplier Credit Notes managed from Accounts Payable application', 'Unit', 'active'),
  (27, 'Supplier Invoice Items', 'Supplier Invoice Items managed from Accounts Payable application', 'Unit', 'active'),
  (28, 'Supplier Invoices', 'Supplier Invoices managed from Accounts Payable application', 'Unit', 'active'),
  (29, 'Supplier Payment Items', 'Supplier Payment Items managed from Accounts Payable application', 'Unit', 'active'),
  (30, 'Supplier Payments', 'Supplier Payments managed from Accounts Payable application', 'Unit', 'active'),
  (31, 'Supplier Payments Allocation', 'Supplier Payments Allocation managed from Accounts Payable application', 'Unit', 'active'),
  (32, 'Collaborators', 'Collaborators managed from HR application', 'Unit', 'active'),
  (33, 'Collaborators Contracts', 'Collaborators Contracts managed from HR application', 'Unit', 'active'),
  (34, 'Collaborators Time Entries', 'Collaborators Time Entries managed from HR application', 'Unit', 'active'),
  (35, 'Payroll Adjustments', 'Payroll Adjustments managed from Payrolls application', 'Unit', 'active'),
  (36, 'Payroll Entries', 'Payroll Entries managed from Payrolls application', 'Unit', 'active'),
  (37, 'Payroll Runs', 'Payroll Runs managed from Payrolls application', 'Unit', 'active'),
  (38, 'Payroll Tax Detail', 'Payroll Tax Detail managed from Payrolls application', 'Unit', 'active'),
  (39, 'Actual Cost Variance', ' Actual Cost Variance managed from Food Costing application', 'Unit', 'active'),
  (40, 'Recipe Ingredients', 'Recipe Ingredients managed from Food Costing application', 'Unit', 'active'),
  (41, 'Recipes', 'Recipes managed from Food Costing application', 'Unit', 'active'),
  (42, 'Theoretical Cost', 'Theoretical Cost managed from Food Costing application', 'Unit', 'active'),
  (43, 'Category Management', 'Category Management managed from Products/Inventory System application', 'Unit', 'active'),
  (44, 'Modifiers Management', 'Modifiers Management managed from Products/Inventory System application', 'Unit', 'active'),
  (45, 'Product Managment', 'Product Managment managed from Products/Inventory System application', 'Unit', 'active'),
  (46, 'Purchase Orders Management', 'Purchase Orders Management managed from Products/Inventory System application', 'Unit', 'active'),
  (47, 'Stock and Stock Movements Management', 'Stock and Stock Movements Management managed from Products/Inventory System application', 'Unit', 'active'),
  (48, 'Suppliers Management', 'Suppliers Management managed from Products/Inventory System application', 'Unit', 'active'),
  (49, 'Variants Management', 'Variants Management managed from Products/Inventory System application', 'Unit', 'active'),
  (50, 'Floor plans', 'Floor plans managed from Dining System application', 'Unit', 'active'),
  (51, 'Table asignments', 'Table asignments managed from Dining System application', 'Unit', 'active'),
  (52, 'Table Zones', 'Table Zones managed from Dining System application', 'Unit', 'active'),
  (53, 'Tables', 'Tables managed from Dining System application', 'Unit', 'active'),
  (54, 'Kitchen Display Devices', 'Kitchen Display Devices managed from Kitchen Display System application', 'Unit', 'active'),
  (55, 'Kitchen Event Log', 'Kitchen Event Log managed from Kitchen Display System application', 'Unit', 'active'),
  (56, 'Kitchen Order Items', 'Kitchen Order Items managed from Kitchen Display System application', 'Unit', 'active'),
  (57, 'Kitchen Orders', 'Kitchen Orders managed from Kitchen Display System application', 'Unit', 'active'),
  (58, 'Kitchen Stations', 'Kitchen Stations managed from Kitchen Display System application', 'Unit', 'active'),
  (59, 'Order Discounts', 'Order Discounts managed from POS application', 'Unit', 'active'),
  (60, 'Order Items', 'Order Items managed from POS application', 'Unit', 'active'),
  (61, 'Order Payments', 'Order Payments managed from POS application', 'Unit', 'active'),
  (62, 'Order Taxes', 'Order Taxes managed from POS application', 'Unit', 'active'),
  (63, 'Orders', 'Orders managed from POS application', 'Unit', 'active'),
  (64, 'Order Item Modifiers', 'Order Item Modifiers managed from POS application', 'Unit', 'active'),
  (65, 'Cash Drawer History', 'Cash Drawer History managed from Cash Drawers application', 'Unit', 'active'),
  (66, 'Cash Drawers', 'Cash Drawers managed from Cash Drawers application', 'Unit', 'active'),
  (67, 'Cash Transactions', 'Cash Transactions managed from Cash Drawers application', 'Unit', 'active'),
  (68, 'Shift Assignment', 'Shift Assignment managed from Shifts application', 'Unit', 'active'),
  (69, 'Shifts', 'Shifts managed from Shifts application', 'Unit', 'active'),
  (70, 'Tip movements', 'Tip movements managed from Tips application', 'Unit', 'active'),
  (71, 'Tip pool members', 'Tip pool members managed from Tips application', 'Unit', 'active'),
  (72, 'Tip settlements', 'Tip settlements managed from Tips application', 'Unit', 'active'),
  (73, 'Tips', 'Tips managed from Tips application', 'Unit', 'active'),
  (74, 'Tips Allocations', 'Tips Allocations managed from Tips application', 'Unit', 'active'),
  (75, 'Tips pools', 'Tips pools managed from Tips application', 'Unit', 'active'),
  (76, 'Reservations', 'Reservations managed from Reservations application', 'Unit', 'active'),
  (77, 'Reservation Guests', 'Reservation Guests managed from Reservations application', 'Unit', 'active'),
  (78, 'Reservation Notes', 'Reservation Notes managed from Reservations application', 'Unit', 'active'),
  (79, 'Reservation Status History', 'Reservation Status History managed from Reservations application', 'Unit', 'active'),
  (80, 'Reservation Tables', 'Reservation Tables managed from Reservations application', 'Unit', 'active'),
  (81, 'Table Turnover Optimization', 'Table Turnover Optimization managed from Table Turnover Optimization application', 'Unit', 'active'),
  (82, 'Delivery Assignments', 'Delivery Assignments managed from Delivery Management application', 'Unit', 'active'),
  (83, 'Delivery Drivers', 'Delivery Drivers managed from Delivery Management application', 'Unit', 'active'),
  (84, 'Delivery Fees', 'Delivery Fees managed from Delivery Management application', 'Unit', 'active'),
  (85, 'Delivery Tracking', 'Delivery Tracking managed from Delivery Management application', 'Unit', 'active'),
  (86, 'Delivery Zones', 'Delivery Zones managed from Delivery Management application', 'Unit', 'active'),
  (87, 'Online Delivery Info', 'Online Delivery Info managed from Online Ordering System application', 'Unit', 'active'),
  (88, 'Online Menu Categories', 'Online Menu Categories managed from Online Ordering System application', 'Unit', 'active'),
  (89, 'Online Menu Items', 'Online Menu Items managed from Online Ordering System application', 'Unit', 'active'),
  (90, 'Online Menus', 'Online Menus managed from Online Ordering System application', 'Unit', 'active'),
  (91, 'Online Order Items', 'Online Order Items managed from Online Ordering System application', 'Unit', 'active'),
  (92, 'Online Orders', 'Online Orders managed from Online Ordering System application', 'Unit', 'active'),
  (93, 'Online Payments', 'Online Payments managed from Online Ordering System application', 'Unit', 'active'),
  (94, 'Online Stores', 'Online Stores managed from Online Ordering System application', 'Unit', 'active'),
  (95, 'QR Code Locations', 'QR Code Locations managed from QR Code System application', 'Unit', 'active'),
  (96, 'QR Code Menu Items', 'QR Code Menu Items managed from QR Code System application', 'Unit', 'active'),
  (97, 'QR Code Menu Sections', 'QR Code Menu Sections managed from QR Code System application', 'Unit', 'active'),
  (98, 'QR Code Menus', 'QR Code Menus managed from QR Code System application', 'Unit', 'active'),
  (99, 'QR Code Orders', 'QR Code Orders managed from QR Code System application', 'Unit', 'active'),
  (100, 'QR Order Items', 'QR Order Items managed from QR Code System application', 'Unit', 'active'),
  (101, 'Loyalty costumers', 'Loyalty costumers managed from Loyalty System application', 'Unit', 'active'),
  (102, 'Loyalty coupons', 'Loyalty coupons managed from Loyalty System application', 'Unit', 'active'),
  (103, 'Loyalty point transactions', 'Loyalty point transactions managed from Loyalty System application', 'Unit', 'active'),
  (104, 'Loyalty Programs', 'Loyalty Programs managed from Loyalty System application', 'Unit', 'active'),
  (105, 'Loyalty rewards', 'Loyalty rewards managed from Loyalty System application', 'Unit', 'active'),
  (106, 'Loyalty rewards redemptions', 'Loyalty rewards redemptions managed from Loyalty System application', 'Unit', 'active'),
  (107, 'Loyalty tiers', 'Loyalty tiers managed from Loyalty System application', 'Unit', 'active'),
  (108, 'Marketing Automation', 'Marketing Automation managed from Loyalty System application Marketing System', 'Unit', 'active'),
  (109, 'Marketing Automation Action', 'Marketing Automation Action managed from Loyalty System application Marketing System', 'Unit', 'active'),
  (110, 'Marketing Campaign', 'Marketing Campaign managed from Loyalty System application Marketing System', 'Unit', 'active'),
  (111, 'Marketing Campaign Audience', 'Marketing Campaign Audience managed from Loyalty System application Marketing System', 'Unit', 'active'),
  (112, 'Marketing Coupon', 'Marketing Coupon managed from Loyalty System application Marketing System', 'Unit', 'active'),
  (113, 'Marketing Coupon Redemption', 'Marketing Coupon Redemption managed from Loyalty System application Marketing System', 'Unit', 'active'),
  (114, 'Marketing Message Log', 'Marketing Message Log managed from Loyalty System application Marketing System', 'Unit', 'active'),
  (115, 'Marketing Segment', 'Marketing Segment managed from Loyalty System application Marketing System', 'Unit', 'active'),
  (116, 'Marketing Segment Rule', 'Marketing Segment Rule managed from Loyalty System application Marketing System', 'Unit', 'active')
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  "Unit" = EXCLUDED."Unit",
  status = EXCLUDED.status;

INSERT INTO plan_applications (subscriptionplan_id, application_id, limits, status) VALUES
  (1, 1, 'unlimited', 'active'),
  (1, 2, 'unlimited', 'active'),
  (1, 3, 'unlimited', 'active'),
  (1, 4, 'unlimited', 'active'),
  (1, 5, 'unlimited', 'active'),
  (1, 6, 'unlimited', 'active'),
  (1, 7, 'unlimited', 'active'),
  (1, 10, 'unlimited', 'active'),
  (1, 15, 'unlimited', 'active'),
  (1, 16, 'unlimited', 'active'),
  (1, 17, 'unlimited', 'active'),
  (1, 18, 'unlimited', 'active'),
  (1, 19, 'unlimited', 'active'),
  (1, 20, 'unlimited', 'active'),
  (1, 25, 'unlimited', 'active'),
  (2, 1, 'unlimited', 'active'),
  (2, 2, 'unlimited', 'active'),
  (2, 3, 'unlimited', 'active'),
  (2, 4, 'unlimited', 'active'),
  (2, 5, 'unlimited', 'active'),
  (2, 6, 'unlimited', 'active'),
  (2, 7, 'unlimited', 'active'),
  (2, 8, 'unlimited', 'active'),
  (2, 9, 'unlimited', 'active'),
  (2, 10, 'unlimited', 'active'),
  (2, 11, 'unlimited', 'active'),
  (2, 12, 'unlimited', 'active'),
  (2, 13, 'unlimited', 'active'),
  (2, 14, 'unlimited', 'active'),
  (2, 15, 'unlimited', 'active'),
  (2, 16, 'unlimited', 'active'),
  (2, 17, 'unlimited', 'active'),
  (2, 18, 'unlimited', 'active'),
  (2, 19, 'unlimited', 'active'),
  (2, 20, 'unlimited', 'active'),
  (2, 21, 'unlimited', 'active'),
  (2, 22, 'unlimited', 'active'),
  (2, 23, 'unlimited', 'active'),
  (2, 24, 'unlimited', 'active'),
  (2, 25, 'unlimited', 'active'),
  (2, 26, 'unlimited', 'active'),
  (3, 1, 'unlimited', 'active'),
  (3, 2, 'unlimited', 'active'),
  (3, 3, 'unlimited', 'active'),
  (3, 4, 'unlimited', 'active'),
  (3, 5, 'unlimited', 'active'),
  (3, 6, 'unlimited', 'active'),
  (3, 7, 'unlimited', 'active'),
  (3, 8, 'unlimited', 'active'),
  (3, 9, 'unlimited', 'active'),
  (3, 10, 'unlimited', 'active'),
  (3, 11, 'unlimited', 'active'),
  (3, 12, 'unlimited', 'active'),
  (3, 13, 'unlimited', 'active'),
  (3, 14, 'unlimited', 'active'),
  (3, 15, 'unlimited', 'active'),
  (3, 16, 'unlimited', 'active'),
  (3, 17, 'unlimited', 'active'),
  (3, 18, 'unlimited', 'active'),
  (3, 19, 'unlimited', 'active'),
  (3, 20, 'unlimited', 'active'),
  (3, 21, 'unlimited', 'active'),
  (3, 22, 'unlimited', 'active'),
  (3, 23, 'unlimited', 'active'),
  (3, 24, 'unlimited', 'active'),
  (3, 25, 'unlimited', 'active'),
  (3, 26, 'unlimited', 'active'),
  (3, 27, 'unlimited', 'active'),
  (3, 28, 'unlimited', 'active');

INSERT INTO plan_features (subscription_plan_id, feature_id, limit_value, status) VALUES
  (1, 1, 0, 'active'),
  (1, 2, 0, 'active'),
  (1, 3, 0, 'active'),
  (1, 4, 0, 'active'),
  (1, 5, 0, 'active'),
  (1, 6, 0, 'active'),
  (1, 7, 0, 'active'),
  (1, 8, 0, 'active'),
  (1, 9, 0, 'active'),
  (1, 10, 0, 'active'),
  (1, 11, 0, 'active'),
  (1, 12, 0, 'active'),
  (1, 13, 0, 'active'),
  (1, 14, 0, 'active'),
  (1, 15, 0, 'active'),
  (1, 16, 0, 'active'),
  (1, 24, 0, 'active'),
  (1, 43, 0, 'active'),
  (1, 44, 0, 'active'),
  (1, 45, 0, 'active'),
  (1, 49, 0, 'active'),
  (1, 53, 0, 'active'),
  (1, 56, 0, 'active'),
  (1, 57, 0, 'active'),
  (1, 59, 0, 'active'),
  (1, 60, 0, 'active'),
  (1, 61, 0, 'active'),
  (1, 62, 0, 'active'),
  (1, 63, 0, 'active'),
  (1, 64, 0, 'active'),
  (1, 66, 0, 'active'),
  (1, 67, 0, 'active'),
  (1, 69, 0, 'active'),
  (1, 91, 0, 'active'),
  (1, 92, 0, 'active'),
  (1, 93, 0, 'active'),
  (2, 1, 0, 'active'),
  (2, 2, 0, 'active'),
  (2, 3, 0, 'active'),
  (2, 4, 0, 'active'),
  (2, 5, 0, 'active'),
  (2, 6, 0, 'active'),
  (2, 7, 0, 'active'),
  (2, 8, 0, 'active'),
  (2, 9, 0, 'active'),
  (2, 10, 0, 'active'),
  (2, 11, 0, 'active'),
  (2, 12, 0, 'active'),
  (2, 13, 0, 'active'),
  (2, 14, 0, 'active'),
  (2, 15, 0, 'active'),
  (2, 16, 0, 'active'),
  (2, 17, 0, 'active'),
  (2, 18, 0, 'active'),
  (2, 19, 0, 'active'),
  (2, 20, 0, 'active'),
  (2, 21, 0, 'active'),
  (2, 22, 0, 'active'),
  (2, 23, 0, 'active'),
  (2, 24, 0, 'active'),
  (2, 25, 0, 'active'),
  (2, 26, 0, 'active'),
  (2, 27, 0, 'active'),
  (2, 28, 0, 'active'),
  (2, 29, 0, 'active'),
  (2, 30, 0, 'active'),
  (2, 31, 0, 'active'),
  (2, 32, 0, 'active'),
  (2, 33, 0, 'active'),
  (2, 34, 0, 'active'),
  (2, 35, 0, 'active'),
  (2, 36, 0, 'active'),
  (2, 37, 0, 'active'),
  (2, 38, 0, 'active'),
  (2, 39, 0, 'active'),
  (2, 40, 0, 'active'),
  (2, 41, 0, 'active'),
  (2, 42, 0, 'active'),
  (2, 43, 0, 'active'),
  (2, 44, 0, 'active'),
  (2, 45, 0, 'active'),
  (2, 46, 0, 'active'),
  (2, 47, 0, 'active'),
  (2, 48, 0, 'active'),
  (2, 49, 0, 'active'),
  (2, 50, 0, 'active'),
  (2, 51, 0, 'active'),
  (2, 52, 0, 'active'),
  (2, 53, 0, 'active'),
  (2, 54, 0, 'active'),
  (2, 55, 0, 'active'),
  (2, 56, 0, 'active'),
  (2, 57, 0, 'active'),
  (2, 58, 0, 'active'),
  (2, 59, 0, 'active'),
  (2, 60, 0, 'active'),
  (2, 61, 0, 'active'),
  (2, 62, 0, 'active'),
  (2, 63, 0, 'active'),
  (2, 64, 0, 'active'),
  (2, 65, 0, 'active'),
  (2, 66, 0, 'active'),
  (2, 67, 0, 'active'),
  (2, 68, 0, 'active'),
  (2, 69, 0, 'active'),
  (2, 70, 0, 'active'),
  (2, 71, 0, 'active'),
  (2, 72, 0, 'active'),
  (2, 73, 0, 'active'),
  (2, 74, 0, 'active'),
  (2, 75, 0, 'active'),
  (2, 76, 0, 'active'),
  (2, 77, 0, 'active'),
  (2, 78, 0, 'active'),
  (2, 79, 0, 'active'),
  (2, 80, 0, 'active'),
  (2, 81, 0, 'active'),
  (2, 82, 0, 'active'),
  (2, 83, 0, 'active'),
  (2, 84, 0, 'active'),
  (2, 85, 0, 'active'),
  (2, 86, 0, 'active'),
  (2, 87, 0, 'active'),
  (2, 88, 0, 'active'),
  (2, 89, 0, 'active'),
  (2, 90, 0, 'active'),
  (2, 91, 0, 'active'),
  (2, 92, 0, 'active'),
  (2, 93, 0, 'active'),
  (2, 94, 0, 'active'),
  (2, 95, 0, 'active'),
  (2, 96, 0, 'active'),
  (2, 97, 0, 'active'),
  (2, 98, 0, 'active'),
  (2, 99, 0, 'active'),
  (2, 100, 0, 'active'),
  (3, 1, 0, 'active'),
  (3, 2, 0, 'active'),
  (3, 3, 0, 'active'),
  (3, 4, 0, 'active'),
  (3, 5, 0, 'active'),
  (3, 6, 0, 'active'),
  (3, 7, 0, 'active'),
  (3, 8, 0, 'active'),
  (3, 9, 0, 'active'),
  (3, 10, 0, 'active'),
  (3, 11, 0, 'active'),
  (3, 12, 0, 'active'),
  (3, 13, 0, 'active'),
  (3, 14, 0, 'active'),
  (3, 15, 0, 'active'),
  (3, 16, 0, 'active'),
  (3, 17, 0, 'active'),
  (3, 18, 0, 'active'),
  (3, 19, 0, 'active'),
  (3, 20, 0, 'active'),
  (3, 21, 0, 'active'),
  (3, 22, 0, 'active'),
  (3, 23, 0, 'active'),
  (3, 24, 0, 'active'),
  (3, 25, 0, 'active'),
  (3, 26, 0, 'active'),
  (3, 27, 0, 'active'),
  (3, 28, 0, 'active'),
  (3, 29, 0, 'active'),
  (3, 30, 0, 'active'),
  (3, 31, 0, 'active'),
  (3, 32, 0, 'active'),
  (3, 33, 0, 'active'),
  (3, 34, 0, 'active'),
  (3, 35, 0, 'active'),
  (3, 36, 0, 'active'),
  (3, 37, 0, 'active'),
  (3, 38, 0, 'active'),
  (3, 39, 0, 'active'),
  (3, 40, 0, 'active'),
  (3, 41, 0, 'active'),
  (3, 42, 0, 'active'),
  (3, 43, 0, 'active'),
  (3, 44, 0, 'active'),
  (3, 45, 0, 'active'),
  (3, 46, 0, 'active'),
  (3, 47, 0, 'active'),
  (3, 48, 0, 'active'),
  (3, 49, 0, 'active'),
  (3, 50, 0, 'active'),
  (3, 51, 0, 'active'),
  (3, 52, 0, 'active'),
  (3, 53, 0, 'active'),
  (3, 54, 0, 'active'),
  (3, 55, 0, 'active'),
  (3, 56, 0, 'active'),
  (3, 57, 0, 'active'),
  (3, 58, 0, 'active'),
  (3, 59, 0, 'active'),
  (3, 60, 0, 'active'),
  (3, 61, 0, 'active'),
  (3, 62, 0, 'active'),
  (3, 63, 0, 'active'),
  (3, 64, 0, 'active'),
  (3, 65, 0, 'active'),
  (3, 66, 0, 'active'),
  (3, 67, 0, 'active'),
  (3, 68, 0, 'active'),
  (3, 69, 0, 'active'),
  (3, 70, 0, 'active'),
  (3, 71, 0, 'active'),
  (3, 72, 0, 'active'),
  (3, 73, 0, 'active'),
  (3, 74, 0, 'active'),
  (3, 75, 0, 'active'),
  (3, 76, 0, 'active'),
  (3, 77, 0, 'active'),
  (3, 78, 0, 'active'),
  (3, 79, 0, 'active'),
  (3, 80, 0, 'active'),
  (3, 81, 0, 'active'),
  (3, 82, 0, 'active'),
  (3, 83, 0, 'active'),
  (3, 84, 0, 'active'),
  (3, 85, 0, 'active'),
  (3, 86, 0, 'active'),
  (3, 87, 0, 'active'),
  (3, 88, 0, 'active'),
  (3, 89, 0, 'active'),
  (3, 90, 0, 'active'),
  (3, 91, 0, 'active'),
  (3, 92, 0, 'active'),
  (3, 93, 0, 'active'),
  (3, 94, 0, 'active'),
  (3, 95, 0, 'active'),
  (3, 96, 0, 'active'),
  (3, 97, 0, 'active'),
  (3, 98, 0, 'active'),
  (3, 99, 0, 'active'),
  (3, 100, 0, 'active'),
  (3, 101, 0, 'active'),
  (3, 102, 0, 'active'),
  (3, 103, 0, 'active'),
  (3, 104, 0, 'active'),
  (3, 105, 0, 'active'),
  (3, 106, 0, 'active'),
  (3, 107, 0, 'active'),
  (3, 108, 0, 'active'),
  (3, 109, 0, 'active'),
  (3, 110, 0, 'active'),
  (3, 111, 0, 'active'),
  (3, 112, 0, 'active'),
  (3, 113, 0, 'active'),
  (3, 114, 0, 'active'),
  (3, 115, 0, 'active'),
  (3, 116, 0, 'active');

SELECT setval(pg_get_serial_sequence('subscription_plan', 'id'), (SELECT COALESCE(MAX(id), 1) FROM subscription_plan));
SELECT setval(pg_get_serial_sequence('application', 'id'), (SELECT COALESCE(MAX(id), 1) FROM application));
SELECT setval(pg_get_serial_sequence('feature', 'id'), (SELECT COALESCE(MAX(id), 1) FROM feature));
SELECT setval(pg_get_serial_sequence('plan_applications', 'id'), (SELECT COALESCE(MAX(id), 1) FROM plan_applications));
SELECT setval(pg_get_serial_sequence('plan_features', 'id'), (SELECT COALESCE(MAX(id), 1) FROM plan_features));
COMMIT;
